#!/bin/bash

map_hook="/usr/share/lve/dbgovernor2/utils/dbgovernor_map"
mysql_hook="/usr/share/lve/dbgovernor2/scripts/mysql_hook"
hook_manager="/usr/local/cpanel/bin/manage_hooks"

####################################################
# Standardized hooks list                                       #
####################################################
"$hook_manager" del script "$map_hook" --category=Whostmgr --event=Accounts::Create --stage=post --manual 1
"$hook_manager" del script "$map_hook" --category=Whostmgr --event=Accounts::Modify --stage=post --manual 1
"$hook_manager" del script "$map_hook" --category=Whostmgr --event=Accounts::Remove --stage=post --manual 1

"$hook_manager" del script "$mysql_hook" --category=Cpanel --event=UAPI::Mysql::create_user --stage=post --manual 1
"$hook_manager" del script "$mysql_hook" --category=Cpanel --event=UAPI::Mysql::rename_user --stage=post --manual 1
"$hook_manager" del script "$mysql_hook" --category=Cpanel --event=UAPI::Mysql::delete_user --stage=post --manual 1

echo
