#!/usr/bin/perl

my $ver_db = "5.1";
my $ver_cli = "18";
my $ver_cli2 = "15";
my @type_db = _current_mysql_form_file();
if(  lc( $type_db[ 0 ] ) eq "" ){
  @type_db = _current_mysql();
}
print $type_db[ 0 ] . "\n";

if( substr( lc( $type_db[ 0 ] ), 0, 5 ) eq "mysql" )
{
  $ver_db = substr( $type_db[ 1 ], 0, 3 );
  if( $ver_db eq "5.0" )
  {
    $ver_cli = "18";
    $ver_cli2 = "16";
  }
  if( $ver_db eq "5.1" )
  {
    $ver_cli = "18";
    $ver_cli2 = "15";
  }
  if( $ver_db eq "5.5" )
  {
    $ver_cli = "16";
    $ver_cli2 = "15";
  }
}

if( substr( lc( $type_db[ 0 ] ), 0, 7 ) eq "mariadb" )
{
  $ver_db = substr( $type_db[ 1 ], 0, 3 );
  if( $ver_db eq "5.5" )
  {
    $ver_cli = "16";
    $ver_cli2 = "15";
  }
}

_install_client( $ver_cli, $ver_cli2 );

exit 0;

#-----------------------------------------------
#-----------------------------------------------
sub trim($)
{
    my $string = shift;
    $string =~ s/^\s+//;
    $string =~ s/\s+$//;
    return $string;
}

sub _install_client
{
  $ver_client_ = $_[ 0 ];
  $ver_client1_ = $_[ 1 ];

  open( READ, "rpm -qa | grep -i mysqlclient |" );
  my $curr_client = "";
  while( <READ> )
  {
    $curr_client = $curr_client . trim($_) . " ";
  }
  close( READ );

  system( "rpm -e " . trim($curr_client) . " --nodeps");
  system( "yum install -y mysqlclient" . $ver_client_ . " mysqlclient" . $ver_client1_ . " --enablerepo=cloudlinux-updates-testing --disableexcludes=all" );
}

sub _current_mysql()
{
  open( READ, "rpm -qa | egrep -i 'mysql|mariadb' | grep -i server |" );
  my $result = "";
  my $mysql_name = "";
  my $mysql_ver = "";

  while( <READ> )
  {
    $result = $result . $_;
  }
  close( READ );

  my @res = split( /-/, $result );

  if( lc( $res[ 0 ] ) eq "cl" )
  {
    $mysql_name = $res[ 1 ];
    $mysql_ver = $res[ 3 ];
  }
  else
  {
    $mysql_name = $res[ 0 ];
    $mysql_ver = $res[ 2 ];
  }

  return $mysql_name, $mysql_ver;
}

sub _current_mysql_form_file()
{
my $mysqlTypeFileSet="/usr/share/lve/dbgovernor/mysql.type";
my $mysql_name = "";
my $mysql_ver = "";
if( open( my $mysql_db, "<", $mysqlTypeFileSet ) )
{
  my $type_db = <$mysql_db>;
  if( $type_db ne "auto" )
  {
    if( $type_db eq "mysql50" )
    {
      $mysql_ver="5.0.0";
      $mysql_name="mysql";
    }
    if( $type_db eq "mysql51" )
    {
      $mysql_ver="5.1.0";
      $mysql_name="mysql";
    }
    if( $type_db eq "mysql55" )
    {
      $mysql_ver="5.5.0";
      $mysql_name="mysql";
    }
    if( $type_db eq "mariadb55" )
    {
      $mysql_ver="5.5.0";
      $mysql_name="mariadb";
    }
  }
  close( $mysql_db );
}
return $mysql_name, $mysql_ver;
}