#!/bin/bash

(>&2 "This script is deprecated. Use mysqlgovernor.py --mysql-version instead")

if [ "$1" == "-m" ] || [ "$1" == "--mysql-version" ]; then
    /usr/share/lve/dbgovernor/mysqlgovernor.py --mysql-version $2;
fi;
