#!/usr/bin/perl

_rm_client();

exit 0;

#-----------------------------------------------
#-----------------------------------------------
sub trim($)
{
    my $string = shift;
    $string =~ s/^\s+//;
    $string =~ s/\s+$//;
    return $string;
}

sub _rm_client
{
  open( READ, "rpm -qa | grep -i mysqlclient |" );
  my $curr_client = "";
  while( <READ> )
  {
    $curr_client = $curr_client . trim($_) . " ";
  }
  close( READ );

  system( "rpm -e " . trim($curr_client) . " --nodeps");
}

