#!/bin/bash

. /usr/share/lve/dbgovernor/cpanel/cpanel-common-lve

postupcp="/scripts/postupcp"
mysqluserupdate1="/usr/local/cpanel/hooks/mysql/adduser"
mysqluserupdate2="/usr/local/cpanel/hooks/mysql/deluser"

deleteAllInclude "$postupcp" "postupcp" "/#dbgovernor/d"
deleteAllInclude "$mysqluserupdate1" "mysqluserupdate1" "/#dbgovernor/d"
deleteAllInclude "$mysqluserupdate2" "mysqluserupdate2" "/#dbgovernor/d"

echo
