#!/usr/local/cpanel/3rdparty/bin/perl

#BEGIN { unshift @INC, '/scripts'; }
BEGIN { unshift @INC, '/usr/local/cpanel', '/scripts'; }

my $pckg_name = 'Cpanel';
use strict;

eval "use " .$pckg_name . "::cPPkgs          ();";
if ($@){
    $pckg_name = 'cPScript';
    eval "use " .$pckg_name . "::cPPkgs       ();";
}

eval "use " .$pckg_name . "::SysPkgs              ();";
eval "use  " .$pckg_name . "::Sys 	           ();";
eval "use  " .$pckg_name . "::OSSys                ();";
eval "use  " .$pckg_name . "::HttpRequest          ();";
eval "use  " .$pckg_name . "::Config::LoadCpConf   ();";
eval "use  " .$pckg_name . "::RpmUtils             ();";
eval "use  " .$pckg_name . "::FileUtils::TouchFile ();";

my $mysqlTypeFileSet="/usr/share/lve/dbgovernor/mysql.type";
my $cPanelVersion=`/usr/local/cpanel/cpanel -V | cut -d'.' -f1`;
chomp $cPanelVersion;
my $cPanelsubVersion=`/usr/local/cpanel/cpanel -V | cut -d'.' -f2`;
chomp $cPanelsubVersion;

my $force   = 1;                                                                                                                                             
while ( $#ARGV != -1 ) {                                                                                                                                     
    if ( $ARGV[0] =~ m/^\-\-/ ) {                                                                                                                            
        my $arg = shift @ARGV;                                                                                                                               
        $arg =~ s/^\-\-//g;                                                                                                                                  
        $arg = lc $arg;                                                                                                                                      
        if ( $arg eq 'force' )   { $force   = 1; }                                                                                                           
    }                                                                                                                                                        
    else {                                                                                                                                                   
        last;                                                                                                                                                
    }                                                                                                                                                        
}   

my $httpClient = eval $pckg_name . "::HttpRequest->new( 'hideOutput' => 0 );";
my $url = 'http://repo.cloudlinux.com/cloudlinux';

my ( $system, $nodename, $release, $version, $machine ) = eval $pckg_name . "::OSSys::uname();";
my $system_tp = getSystemType($release);
if ($system_tp eq "") {
    print "Unknown system type --".$release.". Installation aborted\n";
    exit;
}
my $arch = $machine;
if ( $machine =~ /i.86/ ) {
    $arch = 'i386';
}

my %CPCONF =  eval $pckg_name . "::Config::LoadCpConf::loadcpconf();";

# Default to 4 if mysql-version is unset
if (   !exists $CPCONF{'mysql-version'}
    || !defined $CPCONF{'mysql-version'}
    || $CPCONF{'mysql-version'} eq ''
    || $CPCONF{'mysql-version'} eq '3' ) {
    $CPCONF{'mysql-version'} = '4';
}

my $updated = 0;
my $baseurl    = $url . '/sources/cpanel/cl';
my $cPPkg      =  eval $pckg_name . "::cPPkgs->new( 'MySQL', '$baseurl' );";

my $canusecPPkg = ( $cPPkg->haspkg( $CPCONF{'mysql-version'} ) && $CPCONF{'mysql-version'} >= 4 );

my $sql_version = $CPCONF{'mysql-version'};
my $sql_version_2 = $sql_version;
if(!$canusecPPkg){
    my $is_50=index('5.0',$CPCONF{'mysql-version'});
    my $is_51=index('5.1',$CPCONF{'mysql-version'});
    my $is_55=index('5.5',$CPCONF{'mysql-version'});
    my $is_56=index('5.6',$CPCONF{'mysql-version'});
    if (($is_50 == -1) && ($is_51 == -1) && ($is_55 == -1) && ($is_56 == -1)){
	$sql_version = "5.7";
    }
}

if( open( my $mysql_db, "<", $mysqlTypeFileSet ) )
{
  my $type_db = <$mysql_db>;
  if( $type_db ne "auto" )
  {
    if( $type_db eq "mysql50" )
    {
      $sql_version="5.0";
      $sql_version_2=$sql_version;
    }
    if( $type_db eq "mysql51" )
    {
      $sql_version="5.1";
      $sql_version_2=$sql_version;
    }
    if( $type_db eq "mysql55" )
    {
      $sql_version="5.5";
      $sql_version_2=$sql_version;
    }
    if( $type_db eq "mysql56" )
    {
      $sql_version="5.5";
      $sql_version_2="mysql56";
    }
    if( $type_db eq "mariadb55" )
    {
      $sql_version="5.5";
      $sql_version_2="mariadb55";
    }
  }
  close( $mysql_db );
}

#stop mysql beffore reinstall (need for mysql 5.5)
system '/sbin/service', 'mysql', 'stop';


if ($sql_version_2=="5.1"){
    if ( -e '/usr/libexec/mysqld' ) {
	rename '/usr/libexec/mysqld', '/usr/libexec/mysqld.bak'
    }                          
} 

if ($sql_version_2=="5.0"){
    if ( -e '/usr/libexec/mysqld' ) {
	rename '/usr/libexec/mysqld', '/usr/libexec/mysqld.bak'
    }  
} 

if ($sql_version_2=="5.5"){
    if ( -e '/usr/libexec/mysqld' ) {
	rename '/usr/libexec/mysqld', '/usr/libexec/mysqld.bak'
    }  
} 

if ($sql_version_2=="5.6"){
    $sql_version_2="mysql56";
} 

if ($sql_version=="5.5"){
    system '/usr/bin/yum', 'install', 'libaio', '-y';
}

system '/usr/share/lve/dbgovernor/cpanel/check_mysql_leave_pid.sh';

get_repo($sql_version_2, $system_tp);

resmysql();

installMySQLTesting($sql_version_2, $system_tp);

print  "db_governor checking: ";
if (check_package('governor-mysql')){
    print "OK \n";
    system 'chkconfig', '--level', '35', 'db_governor', 'on';                                                                                                                  
    system '/sbin/service', 'db_governor', 'restart';
} else {
    print "FAILED \n";
}

sub installMySQLTesting
{
    my $msql_version = $_[0];
    my $msystem_tp = $_[1];

    if ($msql_version=="5.1") {
	do_command("yum install cl-MySQL-client cl-MySQL-devel cl-MySQL-server cl-MySQL-shared cl-MySQL-bench cl-MySQL-test --nogpgcheck -y --enablerepo=cl-mysql-5.1-testing");
    } elsif ($msql_version=="5.0") {
	do_command("yum install cl-MySQL-bench cl-MySQL-client cl-MySQL-devel cl-MySQL-server cl-MySQL-shared cl-MySQL-bench cl-MySQL-test --nogpgcheck -y --enablerepo=cl-mysql-5.0-testing");
    } elsif ($msql_version=="5.5") {
	do_command("yum install cl-MySQL-client cl-MySQL-devel cl-MySQL-server cl-MySQL-shared cl-MySQL-bench cl-MySQL-test libaio --nogpgcheck -y --enablerepo=cl-mysql-5.5-testing");
    } elsif ($msql_version eq "mariadb55") {
	do_command("yum install cl-mariadb cl-mariadb-bench cl-mariadb-devel cl-mariadb-libs cl-mariadb-server libaio --nogpgcheck -y --enablerepo=cl-mariadb-5.5-testing");
    } elsif ($msql_version eq "mysql56") {
	do_command("yum install cl-MySQL-client cl-MySQL-devel cl-MySQL-server cl-MySQL-shared cl-MySQL-test libaio --nogpgcheck -y --enablerepo=cl-mysql-5.6-testing");
    } else {
	print "Error unknown version\n";
    }
}

sub do_command
{
  my($arg) = shift;
  system("$arg");
  return $? >> 8;
}


sub get_repo {
	my $msql_version = $_[0];
	my $msystem_tp = $_[1];
	my $murl = 'http://repo.cloudlinux.com/other';
	my $burl = "";
	if ($msql_version=="5.1") {$burl = $murl ."/".  $msystem_tp . "/mysqls/cl-mysql-5.1-common.repo";}
	if ($msql_version=="5.0") {$burl = $murl ."/".  $msystem_tp . "/mysqls/cl-mysql-5.0-common.repo";}
	if ($msql_version=="5.5") {$burl = $murl ."/".  $msystem_tp . "/mysqls/cl-mysql-5.5-common.repo";}
	if ($msql_version eq "mariadb55") {$burl = $murl ."/".  $msystem_tp . "/mysqls/cl-mariadb-5.5-common.repo";}
	if ($msql_version eq "mysql56") {$burl = $murl ."/".  $msystem_tp . "/mysqls/cl-mysql-5.6-common.repo";}
	my $res = do_command("wget -O /etc/yum.repos.d/cl-mysql.repo $burl");
        if($res==0){
            	system 'yum', 'clean', 'metadata';
            	if ($msql_version=="mariadb55"){
			print "Repofile /etc/yum.repos.d/cl-mysql.repo installed for $msql_version\n\n";
		} else {
			print "Repofile /etc/yum.repos.d/cl-mysql.repo installed for mysql $msql_version\n\n";
		}
        } else {
		print "\nError on installation. Can't get repo files\n";
        }
}

sub check_package {
    my $pckgname = $_[0];
    open(READ,'rpm -qa | grep ^'.$pckgname.' |');                                                                                                                  
    my $res='';
    while(<READ>){                                                                                                                                               
	$res = $res . $_;                                                                                                                                                    
    } 
    if ($res eq ""){
	return 0;
    } else {
	return 1;
    }
}


sub resmysql {
    if ( -e '/var/cpanel/useapt' && -e '/usr/bin/apt-get' ) {
        system( '/usr/bin/apt-get', '-y', '--fix-broken', 'install' );
    }
    system '/scripts/restartsrv_mysql';
}

sub getSystemType(){
    my $tp = $_[0];
    my $tp2 = $_[1];
    if(index($tp,".el5.")!=-1){
        return "cl5";
    }
    if(index($tp,".el6.")!=-1){
        return "cl6";
    }
    if(-e '/etc/redhat-release'){
	my $redhat_rel5 = `cat /etc/redhat-release | grep "CloudLinux Server release 5."`;
	if ($redhat_rel5 ne "" ){
	    return "cl5";
	}
	my $redhat_rel6 = `cat /etc/redhat-release | grep "CloudLinux Server release 6."`;
	if ($redhat_rel6 ne "" ){
	    return "cl6";
    	}
    }
    if(index($tp2,".el5.")!=-1){
        return "cl5";
    }
    if(index($tp2,".el6.")!=-1){
        return "cl6";
    }
    return "";
}

sub remove_userstat(){
    system "sed", "/userstat/d", "-i", "/etc/my.cnf";
    system "sed", "/userstat_running/d",  "-i", "/etc/my.cnf";
}
