#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - bin/dbmaptool                          Copyright(c) 2010 cPanel, Inc.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;
use Cpanel::Config::Users         ();
use Cpanel::DB::Map               ();
use Cpanel::DB                    ();
use Data::Dumper;

my $mapfilename = "/etc/container/dbuser-map";
my @old = ();
my @new = ();
my @copy_new = ();

if (-e $mapfilename) {
    open(FILENAME, $mapfilename);
    while ( <FILENAME> )
    {
	chomp;
	push @old, [ split / / ];
    }
}

@new = get_map_list_();
@copy_new = map { [@$_] } @new;

my @del_list = ();
my @del_list2 = ();

my $i=0;
my $j=0;
foreach my $item (@new){
    $j=0;
    my $del = 0;
    foreach my $item2 (@old){
	if (($$item[0] eq $$item2[0]) && ($$item[1] eq $$item2[1])){
	    push @del_list, $j;
	    $del = 1;
	} 
	$j++;
    }
    if($del==1){
	push @del_list2, $i;
    } 
    $i++;
}

foreach my $item (@del_list){
    delete $old[$item];
}
foreach my $item (@del_list2){
    delete $new[$item];
}
@old = grep {$_} @old;
@new = grep {$_} @new;

my $cnt_old = @old;
my $cnt_new = @new;

if($cnt_old>0 || $cnt_new>0){
    open (MAPFILE, ">$mapfilename"); 
    foreach my $item (@copy_new){
	print MAPFILE $$item[0], " ", $$item[1], "\n";
    }
    close(MAPFILE);
}

sub get_map_list_ {
    my @arr = ();
    my @users =Cpanel::Config::Users::getcpusers();
    foreach my $user (@users) {
	my $user_map1 = Cpanel::DB::get_map ( {'cpuser' => $user} );
	my $name="";
	my $uid= -1;
	my $dummy;
	($name, $dummy, $uid, $dummy, $dummy, $dummy, $dummy, $dummy, $dummy) = getpwnam($user);
    
	if ($uid>=0 && exists($$user_map1{'stash'}{'MYSQL'}{'dbusers'})){
	    for my $key (keys $$user_map1{'stash'}{'MYSQL'}{'dbusers'}) { 
		push @arr, [ $key, "$uid" ];
	    }
	}
    }
    return @arr;
}
