#!/bin/bash

cpu_limit=
io_limit=

vercomp() {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

is_ver_lt() {
comp=$(python -c "from distutils.version import LooseVersion; print LooseVersion(\"${1}\") < LooseVersion(\"${2}\")")
if [ "$comp" == "True" ];then
	return 1
else
	return 0
fi
}

get_limit(){
  if [ -e /usr/sbin/lvectl ]; then
    container_3=`/usr/sbin/lvectl limits 3 | awk 'NR == 2' | awk '{print $1}'`
    if [[ !  -z  $container_3  ]]; then
        lim_cmd="/usr/sbin/lvectl limits 3"
    else
        lim_cmd="/usr/sbin/lvectl limits default"
    fi
	VERS=`/usr/sbin/lvectl version | cut -d"-" -f1`
	vercomp "1.4" "$VERS"
	VERS_GET=$?
	if [ "$VERS_GET" -eq 1 ];then
    	    LVE_VER=`/usr/sbin/lvectl --lve-version`
    	    if [ "$LVE_VER" == "4" ]; then
        	io_limit="$(${lim_cmd} | awk 'NR == 2' | awk '{print $6}')"
    	    else
        	io_limit="$(${lim_cmd} | awk 'NR == 2' | awk '{print $8}')"
    	    fi
    	    cpu_limit="$(${lim_cmd} | awk 'NR == 2' | awk '{print $2}')"
	else
	    VERS="$(/usr/sbin/lvectl version | awk -F".el" '{print $1}')"
        is_ver_lt "1.5-47.4" "$VERS"
        VERS_GET=$?
        if [ "$VERS_GET" -eq 1 ];then
	        LVE_VER=`/usr/sbin/lvectl --lve-version`
    	    if [ "$LVE_VER" == "4" ]; then
        	io_limit="$(${lim_cmd} --skip-custom | awk 'NR == 2' | awk '{print $6}')"
    	    else
        	io_limit="$(${lim_cmd} --skip-custom | awk 'NR == 2' | awk '{print $8}')"
    	    fi
    	    cpu_limit="$(${lim_cmd} --skip-custom | awk 'NR == 2' | awk '{print $2}')"
    	else
    	    LVE_VER=`/usr/sbin/lvectl --lve-version`
    	    if [ "$LVE_VER" == "4" ]; then
        	io_limit="$(${lim_cmd} | awk 'NR == 2' | awk '{print $6}')"
    	    else
        	io_limit="$(${lim_cmd} | awk 'NR == 2' | awk '{print $8}')"
    	    fi
    	    cpu_limit="$(${lim_cmd} | awk 'NR == 2' | awk '{print $2}')"
    	fi
	fi
  fi
}

set_big_limit(){
    if [ -e /usr/sbin/lvectl ]; then
	VERS=`/usr/sbin/lvectl version | cut -d"-" -f1`
	vercomp "1.4" "$VERS"
	VERS_GET=$?
	if [ "$VERS_GET" -eq 1 ];then
	    if [ -e /usr/sbin/lvectl ]; then
		/usr/sbin/lvectl set 3 --cpu=100 --io=0 --save-all-parameters
	    fi
	else
	    proc_numb=`cat /proc/cpuinfo | grep processor | wc -l`
	    let "max_limit = $proc_numb * 100";
	    VERS="$(/usr/sbin/lvectl version | awk -F".el" '{print $1}')"
        is_ver_lt "1.5-47.4" "$VERS"
        VERS_GET=$?
        if [ "$VERS_GET" -eq 1 ];then
	        /usr/sbin/lvectl set 3 --speed=$max_limit% --io=0 --save-all-parameters --skip-custom
	    else
	        /usr/sbin/lvectl set 3 --speed=$max_limit% --io=0 --save-all-parameters
	    fi
	fi
    fi
}

set_old_limit(){
    if [ -e /usr/sbin/lvectl ]; then
	VERS=`/usr/sbin/lvectl version | cut -d"-" -f1`
	vercomp "1.4" "$VERS"
	VERS_GET=$?
	if [ "$VERS_GET" -eq 1 ];then
	    if [ -z "$io_limit" ]; then
		/usr/sbin/lvectl set 3 --cpu=$cpu_limit --save-all-parameters
	    else
		/usr/sbin/lvectl set 3 --cpu=$cpu_limit --io=$io_limit --save-all-parameters
	    fi
	else
	    VERS="$(/usr/sbin/lvectl version | awk -F".el" '{print $1}')"
        is_ver_lt "1.5-47.4" "$VERS"
        VERS_GET=$?
        if [ "$VERS_GET" -eq 1 ];then
            if [ -z "$io_limit" ]; then
            /usr/sbin/lvectl set 3 --speed=$cpu_limit% --save-all-parameters --skip-custom
            else
            /usr/sbin/lvectl set 3 --speed=$cpu_limit% --io=$io_limit --save-all-parameters --skip-custom
            fi
        else
            if [ -z "$io_limit" ]; then
            /usr/sbin/lvectl set 3 --speed=$cpu_limit% --save-all-parameters
            else
            /usr/sbin/lvectl set 3 --speed=$cpu_limit% --io=$io_limit --save-all-parameters
	        fi
        fi
	fi
    fi
}